# YouTube自動生成システム 統合設定ファイル
# Phase 1: CrewAI WOW Script Creation Crew

# ============================================
# Geminiモデル設定
# ============================================
gemini_models:
  default: gemini-2.5-flash-preview-09-2025

script_generation:
  quality_gate_llm_enabled: true

# ============================================
# 話者設定 (VOICEVOX対応)
# ============================================
speakers:
  - name: 武宏
    display_name: 玄野武宏
    role: 経済アナリスト（男性・専門家）
    voice_id_env: TTS_VOICE_TAKEHIRO
    voicevox_speaker: 11  # 玄野武宏 ノーマル (落ち着いた男性声)
    stability: 0.5
    similarity_boost: 0.75
    style: 0.1
    speaking_style: 落ち着いた、論理的、データ重視
    speaking_pattern: 3文連続で説明 → つむぎに振る
    character_note: 冷静沈着な経済専門家。数字と事実で語る

  - name: つむぎ
    display_name: 春日部つむぎ
    role: 金融レポーター（女性・質問役）
    voice_id_env: TTS_VOICE_TSUMUGI
    voicevox_speaker: 8  # 春日部つむぎ ノーマル (明るい女性声)
    stability: 0.4
    similarity_boost: 0.8
    style: 0.2
    speaking_style: やや早口、リアクション多め、視聴者目線
    speaking_pattern: 短い質問・確認（1文）
    character_note: 好奇心旺盛な若手レポーター。視聴者代表として疑問を投げかける

  - name: ナレーター
    display_name: ナレーション
    role: 導入・まとめ担当
    voice_id_env: TTS_VOICE_NARRATOR
    voicevox_speaker: 3  # ずんだもん ノーマル (ニュートラルな声)
    stability: 0.6
    similarity_boost: 0.7
    style: 0.0
    speaking_style: 明瞭、テンポ良く
    speaking_pattern: 簡潔な要約
    character_note: 中立的なナレーター。導入と締めを担当

# ============================================
# 動画設定
# ============================================
video:
  resolution:
    width: 1920
    height: 1080
  quality_preset: high  # low/medium/high/ultra
  max_duration_minutes: 40
  target_duration_minutes: 8  # デフォルト目標

# ============================================
# ストック映像設定
# ============================================
stock_footage:
  enabled: true
  clips_per_video: 5
  ffmpeg_path: ffmpeg

# ============================================
# メディア品質検証
# ============================================
media_quality:
  enabled: true
  report_dir: "data/qa_reports"
  gating:
    enforce: false
    skip_modes:
      - test
    fail_on_missing_inputs: true
    retry_attempts: 1
    retry_start_step: script_generation
  audio:
    enabled: true
    peak_dbfs_max: -1.0
    rms_dbfs_min: -24.0
    rms_dbfs_max: -10.0
    max_silence_seconds: 1.5
  video:
    enabled: true
    expected_resolution:
      width: 1920
      height: 1080
    min_fps: 24.0
    max_fps: 61.0
    min_bitrate_kbps: 3500
  subtitles:
    enabled: true
    min_line_coverage: 0.9
    max_timing_gap_seconds: 1.5

# ============================================
# 動画レビューAI設定
# ============================================
video_review:
  enabled: true
  screenshot_interval_seconds: 60
  max_screenshots: 15
  output_dir: "output/video_reviews"
  model: gemini-2.5-flash-preview-09-2025
  temperature: 0.4
  max_output_tokens: 2048
  store_feedback: true

subtitle:
  font_size: 48
  color: "&H00FFFF00"  # 黄色 (ASS形式)
  outline_width: 5
  margin_v: 100
  margin_h: 80

thumbnail:
  resolution:
    width: 1280
    height: 720

# ============================================
# 品質基準
# ============================================
quality_thresholds:
  # WOWスコア（10点満点）
  wow_score_min: 8.0
  wow_score_excellent: 9.0

  # 日本語純度は入力より悪化しないことのみを保証（固定閾値なし）

  # 保持率予測（0-100%）
  retention_prediction_min: 50.0
  retention_first_minute_min: 70.0

  # WOW要素の最小数
  surprise_points_min: 5
  emotion_peaks_min: 5
  curiosity_gaps_min: 3
  visual_instructions_min: 15
  concrete_numbers_min: 10
  viewer_questions_min: 3

# ============================================
# CrewAI設定
# ============================================
crew:
  enabled: true
  max_quality_iterations: 2
  parallel_analysis: true  # Agent 1-3を並列実行
  verbose: false

  # エージェント設定
  agents:
    deep_news_analyzer:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.7
      max_tokens: 4096
      timeout_seconds: 120

    curiosity_gap_researcher:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.8
      max_tokens: 2048
      timeout_seconds: 90

    emotional_story_architect:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.8
      max_tokens: 3072
      timeout_seconds: 100

    script_writer:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.9
      max_tokens: 8192
      timeout_seconds: 180

    engagement_optimizer:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.7
      max_tokens: 6144
      timeout_seconds: 120

    quality_guardian:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.5
      max_tokens: 4096
      timeout_seconds: 90

    japanese_purity_polisher:
      model: gemini-2.5-flash-preview-09-2025
      temperature: 0.6
      max_tokens: 8192
      timeout_seconds: 120

  # 保持率予測設定
  retention_predictor:
    interval_seconds: 30
    targets:
      "0-30": 80
      "30-60": 70
      "60-120": 60
      "120-240": 50
      "240-480": 45

# ============================================
# YouTube最適化ルール (2025年版)
# ============================================
youtube_optimization:
  # 最初の8秒ルール
  first_8_seconds:
    enabled: true
    elements:
      - conclusion
      - surprise_number
      - curiosity_question

  # パターン・インタラプト
  pattern_interrupt:
    interval_seconds: 30
    types:
      - graph_display
      - surprise_fact
      - viewer_question
      - example_introduction
      - visual_change

  # PREP法
  prep_method:
    min_usage_count: 3
    structure:
      - Point
      - Reason
      - Example
      - Point

  # 会話リズム
  dialogue_rhythm:
    tanaka_sentences_per_turn: 3
    suzuki_sentences_per_turn: 1
    max_sentence_length: 15  # 文字数

# ============================================
# プロンプト設定
# ============================================
prompts:
  directory: app/config/prompts
  files:
    agents: agents.yaml
    analysis: analysis.yaml
    script_generation: script_generation.yaml
    quality_check: quality_check.yaml

# ============================================
# API設定
# ============================================
api:
  gemini_daily_quota_limit: 0 # Gemini APIの1日あたりのクォータ制限 (0で無効)

# ============================================
# TTS設定
# ============================================
tts:
  max_concurrent: 3
  chunk_size: 1500
  voicevox:
    enabled: true  # VOICEVOX Nemoを有効化（ElevenLabsのバックアップ）
    port: 50121
    speaker: 3  # 話者ID（3: ずんだもん ノーマル - 金融ニュース推奨）
    # 管理スクリプト: scripts/voicevox_manager.sh
    # 起動: ./scripts/voicevox_manager.sh start
    # 停止: ./scripts/voicevox_manager.sh stop
    # ステータス: ./scripts/voicevox_manager.sh status
    # 推奨話者: 3 (ずんだもん), 11 (玄野武宏 男性), 2 (四国めたん 女性)

# ============================================
# デバッグ・ロギング
# ============================================
debug:
  enabled: false
  log_level: INFO  # DEBUG/INFO/WARNING/ERROR
  save_intermediate_files: false
  save_prompts: true

# ============================================
# バックアップ
# ============================================
backup:
  save_local: true
  save_local_backup: true # ローカルバックアップを有効にするか (ENABLED)
  output_dir: output
