services:
  - type: web
    name: youtuber-api
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT app.web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: "10000"
      - fromGroup: youtuber-secrets

  - type: cron
    name: youtuber-daily
    env: python
    runtime: python-3.11
    plan: standard  # メモリとCPUを確保
    schedule: "0 6 * * *"  # 毎日午前6時（UTC）= 日本時間15時
    timeout: 1800  # 30分
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg fonts-ipafont-gothic fonts-ipafont-mincho && \
      pip install --upgrade pip setuptools wheel && \
      pip install -r requirements.txt
    startCommand: "python app/main.py daily"
    envVars:
      - fromGroup: youtuber-secrets

  - type: cron
    name: youtuber-cleanup
    env: python
    plan: starter
    schedule: "0 2 * * 0"  # 日曜2:00 JST
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -c "
      from app.utils import FileUtils
      import os
      # 一時ファイルクリーンアップ
      for directory in ['temp', 'logs']:
          if os.path.exists(directory):
              cleaned = FileUtils.cleanup_old_files(directory, days_old=7)
              print(f'Cleaned {cleaned} files from {directory}')
      "
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - fromGroup: youtuber-secrets

envVarGroups:
  - name: youtuber-secrets
    envVars:
      # AI APIs（必須）
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false

      # 複数APIキー（推奨 - 高可用性のため）
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GEMINI_API_KEY_3
        sync: false

      # Google Services（必須）
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false

      # 通知（推奨）
      - key: DISCORD_WEBHOOK_URL
        sync: false

      # 品質設定（オプション）
      - key: USE_THREE_STAGE_QUALITY_CHECK
        value: "true"
      - key: QUALITY_CHECK_THRESHOLD
        value: "7.0"

      # パフォーマンス設定（オプション）
      - key: MAX_VIDEO_DURATION_MINUTES
        value: "30"
      - key: VIDEO_QUALITY
        value: "high"
      - key: DEBUG
        value: "false"