extends: ./.svelte-kit/tsconfig.json
compilerOptions:
  allowJs: true
  checkJs: false
  types:
    - svelte
include:
  - src/**/*.d.ts
  - src/**/*.ts
  - src/**/*.js
  - src/**/*.svelte
exclude:
  - node_modules
