"""Shared constant values for prompt construction and language policy."""

from .prompts import (  # noqa: F401
    DEFAULT_VIDEO_MODE_CONTEXT,
    JAPANESE_ALLOWED_ECONOMIC_ACRONYMS,
    JAPANESE_ALLOWED_PATTERNS,
    JAPANESE_DIALOGUE_FORMAT,
    JAPANESE_LANGUAGE_RULES,
    METADATA_MODE_CONTEXT,
    METADATA_OTHER_POLICIES_LINES,
    METADATA_REQUIREMENTS_LINES,
    METADATA_TITLE_AVOID_EXAMPLES,
    METADATA_TITLE_POLICY_LINES,
    METADATA_TITLE_SUCCESS_EXAMPLES,
    PURE_JAPANESE_DIRECTIVE,
)
